### ISSUE TITLE
Speeding up the executor?

### ISSUE THREAD

**Issue by fedenusy** [arthurgubaidullin/embed-dependencies#3]
Hi! First off thank you for publishing this, super helpful & works like a charm. Made deploying my Firebase Functions a breeze.

Writing because I noticed that for a barebones Firebase project, the executor takes ~6min to run.

Nx caching helps a little-- but anytime I change something trivial in my functions (like a docstring), the `embed-dependencies` target needs to run again, and I'm in for another ~6min wait.

Is this expected? Any tips on how to speed up the executor?

**Comment by arthurgubaidullin** [comment]
@fedenusy Hi! Thank you for a submitting an issue.

I don't put my code in a functions deployment package, so I didn't notice the problem.

I tried to check on my project, there really is a performance problem.

I'll try to find the problem and fix it.

**Comment by arthurgubaidullin** [comment]
@fedenusy Hi! 

I added a new dependency injector. `yalc` was slow.

You can test on your build.

Install command:
`npm install @arthurgubaidullin/nx-embed-dependencies@next --save-dev`

You also need to explicitly change the configuration to something like this:
```jsonc
{
  // ...
  "targets": {
    // ...
    "embed-dependencies": {
      "executor": "@arthurgubaidullin/nx-embed-dependencies:run",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/packages/lib-with-dependencies",
        "injector": "npm-pack"
      }
    }
  }
  // ...
}
```

Can you check on your project?

**Comment by fedenusy** [comment]
Hi Arthur 👋  Unfortunately I ended up switching to nx-firebase (needed a solution fast), so my repo's no longer compatible with the embed-dependencies plugin. If I bump into another non-firebase use case, I'll come back! For now feel free to close the issue.
