### ISSUE TITLE
NPM Install failing

### ISSUE THREAD

**Issue by dkhunt27** [arthurgubaidullin/embed-dependencies#6]
I am having issue installing package.  I even created a brand new project with `nom init` just to isolate the install

❯ npm install @arthurgubaidullin/nx-embed-dependencies --save-dev
npm ERR! code ENOENT
npm ERR! syscall stat
npm ERR! path /Users/ME/git/node_modules/@arthurgubaidullin/nx-embed-dependencies/libs/@embed-dependencies/npm-pack-injector/embed-dependencies-npm-pack-injector-0.0.1.tgz
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, stat '/Users/ME/git/node_modules/@arthurgubaidullin/nx-embed-dependencies/libs/@embed-dependencies/npm-pack-injector/embed-dependencies-npm-pack-injector-0.0.1.tgz'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by arthurgubaidullin** [comment]
@dkhunt27 What version of node and npm are you using?

**Comment by dkhunt27** [comment]
❯ node -v
v14.21.2
❯ npm -v
6.14.17

also tried with

❯ node -v
v16.18.0
❯ npm -v
8.19.2

**Comment by dkhunt27** [comment]
but does seem to work with
❯ node -v
v16.19.0
❯ npm -v
8.19.3

**Comment by arthurgubaidullin** [comment]
@dkhunt27 I think the minimum node version is 16 for my package.

Thank you. I'll add a minimum version constraint.

**Comment by dkhunt27** [comment]
actually initially I was using yarn add and that is failing on 16.19.0

❯ yarn add @arthurgubaidullin/nx-embed-dependencies
yarn add v1.22.19

[1/4] 🔍  Resolving packages...
error Package "" refers to a non-existing file '"/Users/ME/git/libs/@embed-dependencies/npm-pack-injector/embed-dependencies-npm-pack-injector-0.0.1.tgz"'.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Package "" refers to a non-existing file '"/Users/ME/git/libs/@embed-dependencies/package-json-program/embed-dependencies-package-json-program-0.0.1.tgz"'.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at FileResolver.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:50035:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13

**Comment by arthurgubaidullin** [comment]
@dkhunt27 Checked it doesn't work. I need to think about what can be done.

**Comment by dkhunt27** [comment]
weird it works in npm but not in yarn.

I did check and I think the npm install would have worked for node 16.18.0, but I had mismatch of nx versions.  just FYI on that.

**Comment by arthurgubaidullin** [comment]
@dkhunt27 What version of yarn are you using?

**Comment by dkhunt27** [comment]
yarn v1.22.19... but it also had the same error with 1.22.15

**Comment by arthurgubaidullin** [comment]
@dkhunt27 Thank you. I'll try to fix it. 

While not compatible with yarn, it seems to handle dependencies differently.

**Comment by dkhunt27** [comment]
Is it possible to update the @nrwl and nx dependencies to not be fixed versions?  Maybe use the carrot?  Switched my repo over to npm but my nx project doesn't match "nx": "15.6.3" specifically so I have to override that error/warning

**Comment by arthurgubaidullin** [comment]
@dkhunt27 I tried using the caret character in the dependencies, but Nx replaces them with fixed version values. The thing is that in the new version they also changed the API.

Unfortunately, I can't release a version with caret at the moment.

**Comment by arthurgubaidullin** [comment]
@dkhunt27 I changed the version of nx. Can you check?

`npm install @arthurgubaidullin/nx-embed-dependencies@next`

**Comment by dkhunt27** [comment]
I am seeing the carrot now 

peer nx@"^15.6.3" from @arthurgubaidullin/nx-embed-dependencies@0.2.7
