### ISSUE TITLE
Cannot find module 'node:child_process'

### ISSUE THREAD

**Issue by danplubell** [arthurgubaidullin/embed-dependencies#7]
I'm trying to use this library with nx 15.7.2 and I'm getting the following error:
Cannot find module 'node:child_process' coming from:
/node_modules/.pnpm/@arthurgubaidullin+nx-embed-dependencies@0.2.4_nx@15.7.2/node_modules/@arthurgubaidullin/nx-embed-dependencies/node_modules/@embed-dependencies/npm-pack-injector/src/lib/NpmPackInjector.js

I think I have it configured correctly.  But, I must be overlooking something.

**Comment by arthurgubaidullin** [comment]
@danplubell Hello! Thanks for the feedback!

Can you tell me what version of node are you using?
